/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/base/BaseIcon.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
  }
}
