services:
  frontend:
    container_name: "${PROJECT_PREFIX}-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    networks:
      - custom_network
    environment:
      VITE_SERVER_PORT: ${FRONTEND_PORT}
      VITE_API_URL: ${FRONTEND_API_URL}

  backend:
    container_name: "${PROJECT_PREFIX}-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - custom_network
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      PORT: ${BACKEND_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
