services:
  frontend:
    container_name: "${PROJECT_PREFIX}-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    networks:
      - shared_network
      - internal_network
    environment:
      VITE_SERVER_PORT: ${FRONTEND_PORT}
      VITE_API_URL: ${FRONTEND_API_URL}

  backend:
    container_name: "${PROJECT_PREFIX}-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - internal_network
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      PORT: ${BACKEND_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${GOOGLE_SERVICE_ACCOUNT_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_DRIVE_FOLDER_ID: ${GOOGLE_DRIVE_FOLDER_ID}
